/// Reasoning-effort hint for models that support extended thinking.
///
/// Maps to provider-specific knobs in each gateway implementation:
/// - Ollama: any non-nil value enables `think: true`.
/// - OpenAI (Phase 2): maps to the `reasoning_effort` request parameter on
///   reasoning-capable models.
public enum ReasoningEffort: String, Sendable, Codable, Hashable, CaseIterable {
    case low
    case medium
    case high
}

/// Configuration for a single LLM completion request.
///
/// `CompletionConfig` collects the small set of knobs every provider exposes
/// in some form. Provider-specific options that don't generalise cleanly can
/// be passed through `extraOptions`; gateways forward them verbatim where the
/// underlying API supports it.
public struct CompletionConfig: Sendable, Codable, Hashable {
    /// Sampling temperature; higher values produce more diverse output.
    public var temperature: Double

    /// Hard cap on tokens generated by the model.
    public var maxTokens: Int

    /// Nucleus-sampling cutoff. `nil` defers to the provider default.
    public var topP: Double?

    /// Reasoning-effort hint for models that support extended thinking.
    public var reasoning: ReasoningEffort?

    /// Context window size (Ollama-specific; other providers ignore it).
    public var numCtx: Int?

    /// Provider-specific overrides forwarded verbatim by the gateway.
    public var extraOptions: [String: JSONValue]

    /// Maximum number of recursive tool-call iterations the broker will
    /// dispatch before surfacing `MojenticError.toolDepthExceeded`.
    public var maxToolIterations: Int

    /// Create a `CompletionConfig` with the documented defaults.
    public init(
        temperature: Double = 1.0,
        maxTokens: Int = 16_384,
        topP: Double? = nil,
        reasoning: ReasoningEffort? = nil,
        numCtx: Int? = 32_768,
        extraOptions: [String: JSONValue] = [:],
        maxToolIterations: Int = 25
    ) {
        self.temperature = temperature
        self.maxTokens = maxTokens
        self.topP = topP
        self.reasoning = reasoning
        self.numCtx = numCtx
        self.extraOptions = extraOptions
        self.maxToolIterations = maxToolIterations
    }
}
