/// Reasoning-effort hint for models that support extended thinking.
///
/// Maps to provider-specific knobs in each gateway implementation:
/// - Ollama: any non-nil value enables `think: true`.
/// - OpenAI (Phase 2): maps to the `reasoning_effort` request parameter on
///   reasoning-capable models.
public enum ReasoningEffort: String, Sendable, Codable, Hashable, CaseIterable {
    case low
    case medium
    case high
}

/// Output format requested from the provider.
///
/// Gateways forward the requested format in both ordinary and streaming
/// requests. The format records what was *requested*; it is not proof that
/// the provider enforced it. Callers must still validate the content they
/// receive.
///
/// | Case | OpenAI `response_format` | Ollama `format` |
/// | ---- | ------------------------ | --------------- |
/// | ``text`` | `{"type": "text"}` | omitted |
/// | ``jsonObject`` | `{"type": "json_object"}` | `"json"` |
/// | ``jsonSchema(_:)`` | `{"type": "json_schema", "json_schema": {"name": "response", "schema": …}}` | the schema |
public enum ResponseFormat: Sendable, Codable, Hashable {
    /// Plain text output.
    case text
    /// JSON object mode, without a schema.
    case jsonObject
    /// JSON schema mode constrained by the supplied JSON Schema.
    case jsonSchema(JSONValue)
}

/// Configuration for a single LLM completion request.
///
/// `CompletionConfig` collects the small set of knobs every provider exposes
/// in some form. Provider-specific options that don't generalise cleanly can
/// be passed through `extraOptions`; gateways forward them verbatim where the
/// underlying API supports it.
public struct CompletionConfig: Sendable, Codable, Hashable {
    /// Sampling temperature; higher values produce more diverse output.
    public var temperature: Double

    /// Hard cap on tokens generated by the model.
    public var maxTokens: Int

    /// Nucleus-sampling cutoff. `nil` defers to the provider default.
    public var topP: Double?

    /// Reasoning-effort hint for models that support extended thinking.
    public var reasoning: ReasoningEffort?

    /// Context window size (Ollama-specific; other providers ignore it).
    public var numCtx: Int?

    /// Provider-specific overrides forwarded verbatim by the gateway.
    public var extraOptions: [String: JSONValue]

    /// Maximum number of recursive tool-call iterations the broker will
    /// dispatch before surfacing `MojenticError.toolDepthExceeded`; nil is unlimited.
    public var maxToolIterations: Int?

    /// Output format to request from the provider; `nil` leaves the
    /// provider default and the request body unchanged.
    ///
    /// Forwarded by ordinary and streaming requests. Structured-output calls
    /// (`completeJSON`) derive their own schema and ignore this field.
    public var responseFormat: ResponseFormat?

    /// Create a `CompletionConfig` with the documented defaults.
    public init(
        temperature: Double = 1.0,
        maxTokens: Int = 16_384,
        topP: Double? = nil,
        reasoning: ReasoningEffort? = nil,
        numCtx: Int? = 32_768,
        extraOptions: [String: JSONValue] = [:],
        maxToolIterations: Int? = 25,
        responseFormat: ResponseFormat? = nil
    ) {
        self.temperature = temperature
        self.maxTokens = maxTokens
        self.topP = topP
        self.reasoning = reasoning
        self.numCtx = numCtx
        self.extraOptions = extraOptions
        self.maxToolIterations = maxToolIterations
        self.responseFormat = responseFormat
    }
}
